Import('env')

ccflags = ['-O3', '-m32']

env.StaticLibrary(
    'libpng',
    ['png.c', 'pngset.c', 'pngget.c', 'pngrutil.c', 'pngtrans.c',
     'pngwutil.c', 'pngmem.c', 'pngpread.c', 'pngread.c', 'pngerror.c',
     'pngwrite.c', 'pngrtran.c', 'pngwtran.c', 'pngrio.c', 'pngwio.c'],
    LIBS=['z', 'zopfli'],
    LIBPATH=['../zopfli_build/'],
    CPPPATH=['../zlib/', '../zopfli/src/zopfli'],
    CCFLAGS = ccflags
)
