extern BOOL const IS_SPRITEBUILDER_PRO;

extern NSInteger const DEFAULT_AUDIO_QUALITY;

extern NSString *const PACKAGE_NAME_SUFFIX;

extern NSString *const PACKAGES_FOLDER_NAME;

extern NSString *const INTERMEDIATE_FILE_LOOKUP_NAME;

extern NSString *const PUBLISHER_CACHE_DIRECTORY_NAME;

extern NSUInteger const PUBLISHING_PACKAGES_ZIP_DEBUG_COMPRESSION;
extern NSUInteger const PUBLISHING_PACKAGES_ZIP_RELEASE_COMPRESSION;

extern NSString *const DEFAULT_OUTPUTDIR_PUBLISHED_PACKAGES;

extern NSString *const PACKAGE_PUBLISH_SETTINGS_FILE_NAME;