NSString *const SnapLayerRefreshLines = @"SnapLayerRefreshLines";

NSString *const ANIMATION_PLAYBACK_WILL_START = @"ANIMATION_PLAYBACK_WILL_START";

NSString *const RESOURCE_PATHS_CHANGED = @"RESOURCE_PATHS_CHANGED";