NSString *const SNAP_LAYER_REFRESH_LINES = @"SNAP_LAYER_REFRESH_LINES";

NSString *const ANIMATION_PLAYBACK_WILL_START = @"ANIMATION_PLAYBACK_WILL_START";

NSString *const RESOURCE_PATH_ADDED = @"RESOURCE_PATH_ADDED";
NSString *const RESOURCE_PATH_REMOVED = @"RESOURCE_PATH_REMOVED";
NSString *const RESOURCE_PATHS_CHANGED = @"RESOURCE_PATHS_CHANGED";
NSString *const RESOURCES_CHANGED = @"RESOURCES_CHANGED";

NSString *const SCENEGRAPH_NODE_DELETED = @"SCENEGRAPH_NODE_DELETED";

NSString *const ALL_LIGHTS_VISIBILITY_CHANGED = @"ALL_LIGHTS_VISIBILITY_CHANGED";
