extern NSString *const PASTEBOARD_TYPE_NODE;
extern NSString *const PASTEBOARD_TYPE_TEXTURE;
extern NSString *const PASTEBOARD_TYPE_TEMPLATE;
extern NSString *const PASTEBOARD_TYPE_SB;
extern NSString *const PASTEBOARD_TYPE_RMRESOURCE;
extern NSString *const PASTEBOARD_TYPE_PLUGINNODE;
extern NSString *const PASTEBOARD_TYPE_WAVE;
extern NSString *const PASTEBOARD_TYPE_JOINTBODY;
extern NSString *const PASTEBOARD_TYPE_EFFECTSPRITE;
extern NSString *const PASTEBOARD_TYPE_EFFECTCONTROL;
extern NSString *const PASTEBOARD_TYPE_LOCALIZATIONEDITORTRANSLATION;
extern NSString *const PASTEBOARD_TYPE_KEYFRAMES;
extern NSString *const PASTEBOARD_TYPE_CHANNELKEYFRAMES;

