#import <Foundation/Foundation.h>

extern NSString *const RESOURCE_PROPERTY_TRIM_SPRITES;

extern NSString *const RESOURCE_PROPERTY_IOS_SOUND;
extern NSString *const RESOURCE_PROPERTY_IOS_SOUND_QUALITY;

extern NSString *const RESOURCE_PROPERTY_ANDROID_SOUND;
extern NSString *const RESOURCE_PROPERTY_ANDROID_SOUND_QUALITY;