#import <Foundation/Foundation.h>

extern NSString *const RESOURCE_PROPERTY_TRIM_SPRITES;

extern NSString *const RESOURCE_PROPERTY_IMAGE_SCALE_FROM;
extern NSString *const RESOURCE_PROPERTY_IMAGE_USEUISCALE;

extern NSString *const RESOURCE_PROPERTY_IS_SMARTSHEET;
extern NSString *const RESOURCE_PROPERTY_LEGACY_KEEP_SPRITES_UNTRIMMED;

extern NSString *const RESOURCE_PROPERTY_IOS_IMAGE_FORMAT;
extern NSString *const RESOURCE_PROPERTY_IOS_IMAGE_DITHER;
extern NSString *const RESOURCE_PROPERTY_IOS_IMAGE_COMPRESS;

extern NSString *const RESOURCE_PROPERTY_ANDROID_IMAGE_FORMAT;
extern NSString *const RESOURCE_PROPERTY_ANDROID_IMAGE_DITHER;
extern NSString *const RESOURCE_PROPERTY_ANDROID_IMAGE_COMPRESS;

extern NSString *const RESOURCE_PROPERTY_IOS_SOUND;
extern NSString *const RESOURCE_PROPERTY_IOS_SOUND_QUALITY;

extern NSString *const RESOURCE_PROPERTY_ANDROID_SOUND;
extern NSString *const RESOURCE_PROPERTY_ANDROID_SOUND_QUALITY;