NSString *const LAST_OPENED_PROJECT_PATH = @"LAST_OPENED_PROJECT_PATH";
NSString *const LAST_VISIT_LEFT_PANEL_VISIBLE = @"LAST_VISIT_LEFT_PANEL_VISIBLE";
NSString *const LAST_VISIT_BOTTOM_PANEL_VISIBLE = @"LAST_VISIT_BOTTOM_PANEL_VISIBLE";
NSString *const LAST_VISIT_RIGHT_PANEL_VISIBLE = @"LAST_VISIT_RIGHT_PANEL_VISIBLE";
NSString *const SECURITY_SCOPED_BOOKMARKS_KEY = @"SECURITY_SCOPED_BOOKMARKS_KEY ";