extern NSString *const LAST_OPENED_PROJECT_PATH;
extern NSString *const LAST_VISIT_LEFT_PANEL_VISIBLE;
extern NSString *const LAST_VISIT_BOTTOM_PANEL_VISIBLE;
extern NSString *const LAST_VISIT_RIGHT_PANEL_VISIBLE;
extern NSString *const SECURITY_SCOPED_BOOKMARKS_KEY;